name: Update Last Update

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config user.name "Oconer49"
          git config user.email "b.uribe@utp.edu.co"
      - name: Update lastUpdate file
        run: date +%s > lastUpdate
      - name: Commit changes
        run: |
          git add lastUpdate
          git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update with latest"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin master