name: Publish new version
on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"  # Esto se ejecutará una vez al día a la medianoche

  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          date +%s > lastUpdate
          git config user.name Oconer49
          git config user.email brahyanuribe13@gmail.com
          git add lastUpdate
          git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update with latest"
          git push origin master